name: beer_ranking
description: Your own beer ranking.  
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.2
  sign_in_with_apple: ^6.1.0
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  intl: ^0.18.1
  dio: ^5.4.3+1
  google_fonts: ^6.2.1
  email_validator: ^2.1.17
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  freezed: ^2.5.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true
  assets:
    - .env

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
