// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_config/flutter_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: FlutterConfig.get('FIREBASE_WEB_API_KEY'),
    appId: FlutterConfig.get('FIREBASE_APP_ID_WEB'),
    messagingSenderId: FlutterConfig.get('FIREBASE_MESSAGING_SENDER_ID_WEB'),
    projectId: FlutterConfig.get('FIREBASE_PROJECT_ID'),
    authDomain: FlutterConfig.get('FIREBASE_AUTH_DOMAIN'),
    storageBucket: FlutterConfig.get('FIREBASE_STORAGE_BUCKET'),
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: FlutterConfig.get('FIREBASE_ANDROID_API_KEY') ?? 'default_value',
    appId: FlutterConfig.get('FIREBASE_APP_ID_ANDROID') ?? 'default_value',
    messagingSenderId: FlutterConfig.get('FIREBASE_MESSAGING_SENDER_ID_WEB') ??
        'default_value',
    projectId: FlutterConfig.get('FIREBASE_PROJECT_ID') ?? 'default_value',
    storageBucket: FlutterConfig.get('FIREBASE_STORAGE_BUCKET'),
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: FlutterConfig.get('FIREBASE_IOS_API_KEY'),
    appId: FlutterConfig.get('FIREBASE_APP_ID_IOS'),
    messagingSenderId: FlutterConfig.get('FIREBASE_MESSAGING_SENDER_ID_WEB'),
    projectId: FlutterConfig.get('FIREBASE_PROJECT_ID'),
    storageBucket: FlutterConfig.get('FIREBASE_STORAGE_BUCKET'),
    iosBundleId: 'com.konradkulak.beerRanking',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: FlutterConfig.get('FIREBASE_MACOS_API_KEY'),
    appId: FlutterConfig.get('FIREBASE_APP_ID_MACOS'),
    messagingSenderId: FlutterConfig.get('FIREBASE_MESSAGING_SENDER_ID_WEB'),
    projectId: FlutterConfig.get('FIREBASE_PROJECT_ID'),
    storageBucket: FlutterConfig.get('FIREBASE_STORAGE_BUCKET'),
    iosBundleId: 'com.konradkulak.beerRanking.RunnerTests',
  );
}
