// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMp0_XQ74-RoRPlZ6gIYr7U_0zXC-aC5M',
    appId: '1:503907765259:web:2a897d95c76b50d0c48b0e',
    messagingSenderId: '503907765259',
    projectId: 'beer-ranking-88',
    authDomain: 'beer-ranking-88.firebaseapp.com',
    storageBucket: 'beer-ranking-88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEHfqTX4C1IE8KuqnYAHImnwddzraeEBo',
    appId: '1:503907765259:android:d73001c94bc77194c48b0e',
    messagingSenderId: '503907765259',
    projectId: 'beer-ranking-88',
    storageBucket: 'beer-ranking-88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPgYsEu5YpX0xPX_043wi2Jut0cUrrJqY',
    appId: '1:503907765259:ios:a43e706c835908bac48b0e',
    messagingSenderId: '503907765259',
    projectId: 'beer-ranking-88',
    storageBucket: 'beer-ranking-88.appspot.com',
    iosBundleId: 'com.konradkulak.beerRanking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPgYsEu5YpX0xPX_043wi2Jut0cUrrJqY',
    appId: '1:503907765259:ios:ec5730b5bda7533bc48b0e',
    messagingSenderId: '503907765259',
    projectId: 'beer-ranking-88',
    storageBucket: 'beer-ranking-88.appspot.com',
    iosBundleId: 'com.konradkulak.beerRanking.RunnerTests',
  );
}
